### ISSUE TITLE
logging in a certain js code

### ISSUE THREAD

**Issue by prof-alazhary** [xeioex/njs-examples#8]
Hi Everyone, 

I'm wondering about the way that I can debug my code while development like adding logs as a following ex:-

```js
function to_lower_case(r, data, flags) {
    console.log("PRINT MY DATA.......", data);
    r.sendBuffer(data.toLowerCase(), flags);
}

export default {to_lower_case};
```

why I can't do like this? Is there any approach to achieve this?

**Comment by xeioex** [comment]
Hi @prof-alazhary,

The reason is that there is no console object in nginx module environment. Actually, there are two existing environments as of now: nginx environment and the shell environment. 

To summarise:
* in nginx environment  all objects described in the [reference](http://nginx.org/en/docs/njs/reference.html)  are available
* in the shell environment all objects from the reference except the objects described in `nginx objects` section are available. In addition, `console` object is also available.

To your question, you may use `r.log(string)`, `r.warn(string)`, `r.error(string)` or `ngx.log(level, string)`

**Comment by prof-alazhary** [comment]
Thanks for the response,
SO, I can apply this like the following:
```js
function to_lower_case(r, data, flags) {
    r.log("PRINT MY DATA.......", data.toString());
    r.sendBuffer(data.toLowerCase(), flags);
}
```
correct?

**Comment by prof-alazhary** [comment]
Hi @xeioex 
I've tried to use `r.log` and `ngx.log` , but It's not appeared at all in the logging of `docker logs` or even in the logs files (`/var/log/nginx/access.log` & `/var/log/nginx/error.log`) inside the container.

```js
function covertTokenToCookie(r) {
    r.subrequest("/token_proxy", { method: "POST" },
        function (reply) {
            var status = reply.status;
            if (status) {
                r.log('---debugging----')
                r.log(reply.toString())
                ngx.log(ngx.INFO, "-->>debug2--->>")
                ngx.log(ngx.INFO, reply.responseBody)
                var response = JSON.parse(reply.responseBody);
                r.headersOut["Set-Cookie"] = `access_token=${response.access_token}`;
                r.return(status, reply.responseBody);
            } else {
                r.return(401);
            }
        }
    );
}
```
did I have missed something to do?

**Comment by xeioex** [comment]
@prof-alazhary 

>did I have missed something to do?

It seems you have to set a proper [error_log level](https://nginx.org/en/docs/ngx_core_module.html) to see the logs.

**Comment by prof-alazhary** [comment]
Thanks so much, @xeioex .
It works now when I added:
```
error_log /var/log/nginx/info.log info;
```
